"""add image_url to posts, remove is_valid from refresh_tokens

Revision ID: 8eb0555cdd5b
Revises: ab89f2e767dc
Create Date: 2025-03-31 20:27:46.199597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb0555cdd5b'
down_revision: Union[str, None] = 'ab89f2e767dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_url', sa.String(), nullable=False))
    op.drop_column('refresh_tokens', 'is_valid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('is_valid', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'image_url')
    # ### end Alembic commands ###
